# Generated by Django 5.1.3 on 2024-11-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
