# Generated by Django 5.1.3 on 2024-11-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='message',
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
