# Generated by Django 5.1.3 on 2024-11-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_member_message_member_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='consent_for_data_use_and_storage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='consent_to_participate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='marital_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='membership_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
