# Generated by Django 5.1.3 on 2024-11-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_rename_consent_for_data_use_and_storage_member_consent_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='consent_data',
            field=models.CharField(blank=True, default='False', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='consent_participate',
            field=models.CharField(blank=True, default='False', max_length=100, null=True),
        ),
    ]
