# Generated by Django 5.1.3 on 2025-03-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_member_consent_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ladies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('marital_status', models.CharField(blank=True, max_length=100, null=True)),
                ('membership_status', models.CharField(blank=True, max_length=100, null=True)),
                ('consent_participate', models.CharField(blank=True, default='False', max_length=100, null=True)),
                ('consent_data', models.CharField(blank=True, default='False', max_length=100, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Ladies',
                'ordering': ['-firstname'],
            },
        ),
        migrations.CreateModel(
            name='Rescue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('marital_status', models.CharField(blank=True, max_length=100, null=True)),
                ('membership_status', models.CharField(blank=True, max_length=100, null=True)),
                ('consent_participate', models.CharField(blank=True, default='False', max_length=100, null=True)),
                ('consent_data', models.CharField(blank=True, default='False', max_length=100, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Rescues',
                'ordering': ['-firstname'],
            },
        ),
        migrations.RenameField(
            model_name='member',
            old_name='membership_status',
            new_name='department',
        ),
    ]
